GET http://139.196.194.51:18081/api/patients/all
content-type:application/json
Accept: application/json


###

POST localhost:18080/api/patient2s/update
content-type:application/json
Accept: application/json

{
  "id":"1214",
  "economy":50
}